export const textStyles = [
  { value: "blog-post", label: "📝 Blog Post" },
  { value: "email", label: "📧 Email" },
  { value: "social-media", label: "📱 Social Media Post" },
  { value: "essay", label: "📄 Essay" },
  { value: "poem", label: "🎭 Poem" },
  { value: "story", label: "📖 Short Story" },
  { value: "script", label: "🎬 Script / Dialogue" },
  { value: "news-article", label: "📰 News Article" },
  { value: "product-description", label: "🛍️ Product Description" },
  { value: "resume", label: "💼 Resume / CV" },
  { value: "cover-letter", label: "✉️ Cover Letter" },
  { value: "speech", label: "🎤 Speech" },
  { value: "tagline", label: "✨ Tagline / Slogan" },
  { value: "summary", label: "📋 Summary" },
  { value: "tutorial", label: "🎓 Tutorial / How-To" },
  { value: "review", label: "⭐ Review" },
];

export const codeLanguages = [
  { value: "javascript", label: "🟨 JavaScript" },
  { value: "typescript", label: "🔷 TypeScript" },
  { value: "python", label: "🐍 Python" },
  { value: "java", label: "☕ Java" },
  { value: "csharp", label: "🟣 C#" },
  { value: "cpp", label: "⚙️ C++" },
  { value: "c", label: "🔧 C" },
  { value: "go", label: "🐹 Go" },
  { value: "rust", label: "🦀 Rust" },
  { value: "php", label: "🐘 PHP" },
  { value: "ruby", label: "💎 Ruby" },
  { value: "swift", label: "🍎 Swift" },
  { value: "kotlin", label: "🟠 Kotlin" },
  { value: "dart", label: "🎯 Dart" },
  { value: "html-css", label: "🌐 HTML / CSS" },
  { value: "sql", label: "🗃️ SQL" },
  { value: "bash", label: "🖥️ Bash / Shell" },
  { value: "react", label: "⚛️ React (JSX/TSX)" },
  { value: "vue", label: "💚 Vue" },
  { value: "angular", label: "🅰️ Angular" },
  { value: "nodejs", label: "🟩 Node.js" },
  { value: "r", label: "📊 R" },
  { value: "scala", label: "🔴 Scala" },
  { value: "lua", label: "🌙 Lua" },
];

export const imageTypes = [
  { value: "realistic-photo", label: "📷 Realistic Photo" },
  { value: "digital-art", label: "🎨 Digital Art" },
  { value: "oil-painting", label: "🖼️ Oil Painting" },
  { value: "watercolor", label: "💧 Watercolor" },
  { value: "pencil-sketch", label: "✏️ Pencil Sketch" },
  { value: "anime", label: "🌸 Anime / Manga" },
  { value: "cartoon", label: "🎭 Cartoon" },
  { value: "pixel-art", label: "👾 Pixel Art" },
  { value: "3d-render", label: "🧊 3D Render" },
  { value: "isometric", label: "📐 Isometric" },
  { value: "logo-design", label: "💎 Logo Design" },
  { value: "icon", label: "🔲 Icon / Flat Design" },
  { value: "abstract", label: "🌀 Abstract Art" },
  { value: "fantasy", label: "🐉 Fantasy / Epic" },
  { value: "sci-fi", label: "🚀 Sci-Fi / Futuristic" },
  { value: "minimalist", label: "⬜ Minimalist" },
  { value: "pop-art", label: "🎪 Pop Art" },
  { value: "comic-book", label: "💥 Comic Book" },
  { value: "sticker", label: "🏷️ Sticker" },
  { value: "product-shot", label: "📸 Product Photography" },
];
